spring:
  application:
     name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javyxx/configserver.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888  # HTTP (Tomcat) port